//! Autogenerated weights for user_profile
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-02-23, STEPS: `20`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// ./target/release/debio
// benchmark
// --chain=dev
// --execution=wasm
// --wasm-execution=compiled
// --pallet=user-profile
// --extrinsic=*
// --steps=20
// --repeat=10
// --heap-pages=4096
// --raw
// --output=./pallets/user-profile/src/weights.rs
// --template=./.maintain/pallet-weight-template.hbs


#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for user_profile.
pub trait WeightInfo {
	fn set_eth_address() -> Weight;
	fn admin_set_eth_address() -> Weight;
	fn update_admin_key() -> Weight;
}

/// Weights for user_profile using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: UserProfile AccountIdByEthAddress (r:0 w:1)
	// Storage: UserProfile EthAddressByAccountId (r:0 w:1)
	fn set_eth_address() -> Weight {
		26_582_000_u64
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	// Storage: UserProfile AdminKey (r:1 w:0)
	// Storage: UserProfile AccountIdByEthAddress (r:0 w:1)
	// Storage: UserProfile EthAddressByAccountId (r:0 w:1)
	fn admin_set_eth_address() -> Weight {
		31_488_000_u64
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	// Storage: UserProfile AdminKey (r:1 w:1)
	fn update_admin_key() -> Weight {
		24_541_000_u64
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: UserProfile AccountIdByEthAddress (r:0 w:1)
	// Storage: UserProfile EthAddressByAccountId (r:0 w:1)
	fn set_eth_address() -> Weight {
		26_582_000_u64
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	// Storage: UserProfile AdminKey (r:1 w:0)
	// Storage: UserProfile AccountIdByEthAddress (r:0 w:1)
	// Storage: UserProfile EthAddressByAccountId (r:0 w:1)
	fn admin_set_eth_address() -> Weight {
		31_488_000_u64
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	// Storage: UserProfile AdminKey (r:1 w:1)
	fn update_admin_key() -> Weight {
		24_541_000_u64
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
