//! Autogenerated weights for customers
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-02-24, STEPS: `20`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// target/release/debio
// benchmark
// --chain=dev
// --execution=wasm
// --wasm-execution=compiled
// --pallet=customers
// --extrinsic=*
// --steps=20
// --repeat=10
// --heap-pages=4096
// --raw
// --output=./pallets/customers/src/weights.rs
// --template=./.maintain/pallet-weight-template.hbs


#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for customers.
pub trait WeightInfo {
	fn register_customer() -> Weight;
	fn update_customer() -> Weight;
	fn deregister_customer() -> Weight;
}

/// Weights for customers using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: Customers Customers (r:1 w:1)
	// Storage: Customers CustomersByCountryRegionCity (r:1 w:1)
	// Storage: Customers CustomerCount (r:1 w:1)
	// Storage: Customers CustomerCountByCountryRegionCity (r:1 w:1)
	fn register_customer() -> Weight {
		59_838_000_u64
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	// Storage: Customers Customers (r:1 w:1)
	// Storage: Customers CustomersByCountryRegionCity (r:2 w:2)
	// Storage: Customers CustomerCountByCountryRegionCity (r:2 w:2)
	fn update_customer() -> Weight {
		85_958_000_u64
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	// Storage: Customers Customers (r:1 w:1)
	// Storage: Customers CustomersByCountryRegionCity (r:1 w:1)
	// Storage: Customers CustomerCountByCountryRegionCity (r:1 w:1)
	// Storage: Customers CustomerCount (r:1 w:1)
	fn deregister_customer() -> Weight {
		67_502_000_u64
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: Customers Customers (r:1 w:1)
	// Storage: Customers CustomersByCountryRegionCity (r:1 w:1)
	// Storage: Customers CustomerCount (r:1 w:1)
	// Storage: Customers CustomerCountByCountryRegionCity (r:1 w:1)
	fn register_customer() -> Weight {
		59_838_000_u64
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	// Storage: Customers Customers (r:1 w:1)
	// Storage: Customers CustomersByCountryRegionCity (r:2 w:2)
	// Storage: Customers CustomerCountByCountryRegionCity (r:2 w:2)
	fn update_customer() -> Weight {
		85_958_000_u64
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	// Storage: Customers Customers (r:1 w:1)
	// Storage: Customers CustomersByCountryRegionCity (r:1 w:1)
	// Storage: Customers CustomerCountByCountryRegionCity (r:1 w:1)
	// Storage: Customers CustomerCount (r:1 w:1)
	fn deregister_customer() -> Weight {
		67_502_000_u64
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
}
