//! Autogenerated weights for genetic_analysts
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-02-07, STEPS: `20`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// ./target/release/debio
// benchmark
// --chain=dev
// --execution=wasm
// --wasm-execution=compiled
// --pallet=genetic-analysts
// --extrinsic=*
// --steps=20
// --repeat=10
// --heap-pages=4096
// --raw
// --output=./pallets/genetic-analysts/src/weights.rs
// --template=./.maintain/pallet-weight-template.hbs


#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for genetic_analysts.
pub trait WeightInfo {
	fn register_genetic_analyst() -> Weight;
	fn update_genetic_analyst() -> Weight;
	fn update_genetic_analyst_verification_status() -> Weight;
	fn deregister_genetic_analyst() -> Weight;
	fn stake_genetic_analyst() -> Weight;
}

/// Weights for genetic_analysts using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: GeneticAnalysts GeneticAnalysts (r:1 w:1)
	// Storage: GeneticAnalysts GeneticAnalystCount (r:1 w:1)
	fn register_genetic_analyst() -> Weight {
		28_715_000_u64
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	// Storage: GeneticAnalysts GeneticAnalysts (r:1 w:1)
	fn update_genetic_analyst() -> Weight {
		28_339_000_u64
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	// Storage: GeneticAnalysts GeneticAnalystVerifierKey (r:1 w:0)
	// Storage: GeneticAnalysts GeneticAnalysts (r:1 w:1)
	fn update_genetic_analyst_verification_status() -> Weight {
		28_944_000_u64
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	// Storage: GeneticAnalysts GeneticAnalysts (r:1 w:1)
	// Storage: GeneticAnalysts GeneticAnalystCount (r:1 w:1)
	fn deregister_genetic_analyst() -> Weight {
		32_857_000_u64
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	// Storage: GeneticAnalysts GeneticAnalysts (r:1 w:1)
	// Storage: System Account (r:2 w:2)
	// Storage: GeneticAnalysts TotalStakeAmount (r:0 w:1)
	fn stake_genetic_analyst() -> Weight {
		80_255_000_u64
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: GeneticAnalysts GeneticAnalysts (r:1 w:1)
	// Storage: GeneticAnalysts GeneticAnalystCount (r:1 w:1)
	fn register_genetic_analyst() -> Weight {
		28_715_000_u64
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	// Storage: GeneticAnalysts GeneticAnalysts (r:1 w:1)
	fn update_genetic_analyst() -> Weight {
		28_339_000_u64
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	// Storage: GeneticAnalysts GeneticAnalystVerifierKey (r:1 w:0)
	// Storage: GeneticAnalysts GeneticAnalysts (r:1 w:1)
	fn update_genetic_analyst_verification_status() -> Weight {
		28_944_000_u64
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	// Storage: GeneticAnalysts GeneticAnalysts (r:1 w:1)
	// Storage: GeneticAnalysts GeneticAnalystCount (r:1 w:1)
	fn deregister_genetic_analyst() -> Weight {
		32_857_000_u64
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	// Storage: GeneticAnalysts GeneticAnalysts (r:1 w:1)
	// Storage: System Account (r:2 w:2)
	// Storage: GeneticAnalysts TotalStakeAmount (r:0 w:1)
	fn stake_genetic_analyst() -> Weight {
		80_255_000_u64
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
}
