//! Autogenerated weights for genetic_analysts
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-04-05, STEPS: `20`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// target/release/debio
// benchmark
// --chain=dev
// --execution=wasm
// --wasm-execution=compiled
// --pallet=genetic-analysts
// --extrinsic=*
// --steps=20
// --repeat=10
// --heap-pages=4096
// --raw
// --output=./pallets/genetic-analysts/src/weights.rs
// --template=./.maintain/pallet-weight-template.hbs


#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for genetic_analysts.
pub trait WeightInfo {
	fn register_genetic_analyst() -> Weight;
	fn update_genetic_analyst() -> Weight;
	fn update_genetic_analyst_verification_status() -> Weight;
	fn update_genetic_analyst_availability_status() -> Weight;
	fn deregister_genetic_analyst() -> Weight;
	fn stake_genetic_analyst() -> Weight;
	fn unstake_genetic_analyst() -> Weight;
	fn retrieve_unstake_amount() -> Weight;
	fn update_minimum_stake_amount() -> Weight;
	fn update_unstake_time() -> Weight;
	fn update_admin_key() -> Weight;
}

/// Weights for genetic_analysts using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: GeneticAnalysts GeneticAnalysts (r:1 w:1)
	// Storage: GeneticAnalysts GeneticAnalystCount (r:1 w:1)
	fn register_genetic_analyst() -> Weight {
		38_494_000_u64
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	// Storage: GeneticAnalysts GeneticAnalysts (r:1 w:1)
	fn update_genetic_analyst() -> Weight {
		39_710_000_u64
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	// Storage: GeneticAnalysts GeneticAnalystVerifierKey (r:1 w:0)
	// Storage: GeneticAnalysts GeneticAnalysts (r:1 w:1)
	fn update_genetic_analyst_verification_status() -> Weight {
		40_485_000_u64
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	// Storage: GeneticAnalysts GeneticAnalysts (r:1 w:1)
	fn update_genetic_analyst_availability_status() -> Weight {
		34_329_000_u64
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	// Storage: GeneticAnalysts GeneticAnalysts (r:1 w:1)
	// Storage: GeneticAnalysts GeneticAnalystCount (r:1 w:1)
	fn deregister_genetic_analyst() -> Weight {
		44_218_000_u64
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	// Storage: GeneticAnalysts GeneticAnalysts (r:1 w:1)
	// Storage: System Account (r:2 w:2)
	// Storage: GeneticAnalysts MinimumStakeAmount (r:1 w:0)
	// Storage: GeneticAnalysts PalletAccount (r:1 w:0)
	// Storage: GeneticAnalysts TotalStakedAmount (r:0 w:1)
	fn stake_genetic_analyst() -> Weight {
		108_034_000_u64
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	// Storage: GeneticAnalysts GeneticAnalysts (r:1 w:1)
	// Storage: GeneticAnalysisOrders PendingGeneticAnalysisOrdersBySeller (r:1 w:0)
	// Storage: Timestamp Now (r:1 w:0)
	// Storage: GeneticAnalysts UnstakeTime (r:1 w:0)
	fn unstake_genetic_analyst() -> Weight {
		47_290_000_u64
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	// Storage: GeneticAnalysts GeneticAnalystVerifierKey (r:1 w:0)
	// Storage: GeneticAnalysts GeneticAnalysts (r:1 w:1)
	// Storage: Timestamp Now (r:1 w:0)
	// Storage: GeneticAnalysts PalletAccount (r:1 w:0)
	// Storage: System Account (r:1 w:1)
	// Storage: GeneticAnalysts TotalStakedAmount (r:0 w:1)
	fn retrieve_unstake_amount() -> Weight {
		91_261_000_u64
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	// Storage: GeneticAnalysts GeneticAnalystVerifierKey (r:1 w:0)
	// Storage: GeneticAnalysts MinimumStakeAmount (r:0 w:1)
	fn update_minimum_stake_amount() -> Weight {
		23_280_000_u64
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	// Storage: GeneticAnalysts GeneticAnalystVerifierKey (r:1 w:0)
	// Storage: GeneticAnalysts UnstakeTime (r:0 w:1)
	fn update_unstake_time() -> Weight {
		22_694_000_u64
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	// Storage: GeneticAnalysts GeneticAnalystVerifierKey (r:1 w:1)
	fn update_admin_key() -> Weight {
		23_228_000_u64
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: GeneticAnalysts GeneticAnalysts (r:1 w:1)
	// Storage: GeneticAnalysts GeneticAnalystCount (r:1 w:1)
	fn register_genetic_analyst() -> Weight {
		38_494_000_u64
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	// Storage: GeneticAnalysts GeneticAnalysts (r:1 w:1)
	fn update_genetic_analyst() -> Weight {
		39_710_000_u64
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	// Storage: GeneticAnalysts GeneticAnalystVerifierKey (r:1 w:0)
	// Storage: GeneticAnalysts GeneticAnalysts (r:1 w:1)
	fn update_genetic_analyst_verification_status() -> Weight {
		40_485_000_u64
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	// Storage: GeneticAnalysts GeneticAnalysts (r:1 w:1)
	fn update_genetic_analyst_availability_status() -> Weight {
		34_329_000_u64
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	// Storage: GeneticAnalysts GeneticAnalysts (r:1 w:1)
	// Storage: GeneticAnalysts GeneticAnalystCount (r:1 w:1)
	fn deregister_genetic_analyst() -> Weight {
		44_218_000_u64
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	// Storage: GeneticAnalysts GeneticAnalysts (r:1 w:1)
	// Storage: System Account (r:2 w:2)
	// Storage: GeneticAnalysts MinimumStakeAmount (r:1 w:0)
	// Storage: GeneticAnalysts PalletAccount (r:1 w:0)
	// Storage: GeneticAnalysts TotalStakedAmount (r:0 w:1)
	fn stake_genetic_analyst() -> Weight {
		108_034_000_u64
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	// Storage: GeneticAnalysts GeneticAnalysts (r:1 w:1)
	// Storage: GeneticAnalysisOrders PendingGeneticAnalysisOrdersBySeller (r:1 w:0)
	// Storage: Timestamp Now (r:1 w:0)
	// Storage: GeneticAnalysts UnstakeTime (r:1 w:0)
	fn unstake_genetic_analyst() -> Weight {
		47_290_000_u64
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	// Storage: GeneticAnalysts GeneticAnalystVerifierKey (r:1 w:0)
	// Storage: GeneticAnalysts GeneticAnalysts (r:1 w:1)
	// Storage: Timestamp Now (r:1 w:0)
	// Storage: GeneticAnalysts PalletAccount (r:1 w:0)
	// Storage: System Account (r:1 w:1)
	// Storage: GeneticAnalysts TotalStakedAmount (r:0 w:1)
	fn retrieve_unstake_amount() -> Weight {
		91_261_000_u64
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	// Storage: GeneticAnalysts GeneticAnalystVerifierKey (r:1 w:0)
	// Storage: GeneticAnalysts MinimumStakeAmount (r:0 w:1)
	fn update_minimum_stake_amount() -> Weight {
		23_280_000_u64
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	// Storage: GeneticAnalysts GeneticAnalystVerifierKey (r:1 w:0)
	// Storage: GeneticAnalysts UnstakeTime (r:0 w:1)
	fn update_unstake_time() -> Weight {
		22_694_000_u64
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	// Storage: GeneticAnalysts GeneticAnalystVerifierKey (r:1 w:1)
	fn update_admin_key() -> Weight {
		23_228_000_u64
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
