//! Autogenerated weights for opinion_benchmarking
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-12-16, STEPS: `20`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/debio
// benchmark
// --chain=dev
// --execution=wasm
// --wasm-execution=compiled
// --pallet=opinion-benchmarking
// --extrinsic=*
// --steps=20
// --repeat=10
// --heap-pages=4096
// --output=./pallets/opinion/src/weights.rs
// --template=./.maintain/pallet-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for opinion_benchmarking.
pub trait WeightInfo { 
	fn create() -> Weight; 
	fn update() -> Weight; 
	fn delete() -> Weight; 
	fn update_admin_key() -> Weight; 
}

/// Weights for opinion_benchmarking using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>); 
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> { 
	// Storage: Opinion OpinionAdminKey (r:1 w:0) 
	// Storage: OpinionRequestor OpinionRequestors (r:1 w:1) 
	// Storage: Opinion OpinionCount (r:1 w:1) 
	// Storage: Timestamp Now (r:1 w:0) 
	// Storage: System Account (r:1 w:0) 
	// Storage: Opinion OpinionCountByOwner (r:1 w:1) 
	// Storage: Opinion OpinionByOwner (r:1 w:1) 
	// Storage: Opinion Opinions (r:0 w:1) 
	fn create() -> Weight { 
		122_600_000_u64 
			.saturating_add(T::DbWeight::get().reads(7_u64)) 
			.saturating_add(T::DbWeight::get().writes(5_u64)) 
	}
	// Storage: Opinion OpinionAdminKey (r:1 w:0) 
	// Storage: Opinion Opinions (r:1 w:1) 
	fn update() -> Weight { 
		59_900_000_u64 
			.saturating_add(T::DbWeight::get().reads(2_u64)) 
			.saturating_add(T::DbWeight::get().writes(1_u64)) 
	}
	// Storage: Opinion OpinionAdminKey (r:1 w:0) 
	// Storage: Opinion Opinions (r:1 w:1) 
	// Storage: OpinionRequestor OpinionRequestors (r:1 w:1) 
	// Storage: Opinion OpinionCount (r:1 w:1) 
	// Storage: Opinion OpinionCountByOwner (r:1 w:1) 
	// Storage: Opinion OpinionByOwner (r:1 w:1) 
	fn delete() -> Weight { 
		99_100_000_u64 
			.saturating_add(T::DbWeight::get().reads(6_u64)) 
			.saturating_add(T::DbWeight::get().writes(5_u64)) 
	}
	// Storage: Opinion OpinionAdminKey (r:1 w:1) 
	fn update_admin_key() -> Weight { 
		35_700_000_u64 
			.saturating_add(T::DbWeight::get().reads(1_u64)) 
			.saturating_add(T::DbWeight::get().writes(1_u64)) 
	}
}

// For backwards compatibility and tests
impl WeightInfo for () { 
	// Storage: Opinion OpinionAdminKey (r:1 w:0) 
	// Storage: OpinionRequestor OpinionRequestors (r:1 w:1) 
	// Storage: Opinion OpinionCount (r:1 w:1) 
	// Storage: Timestamp Now (r:1 w:0) 
	// Storage: System Account (r:1 w:0) 
	// Storage: Opinion OpinionCountByOwner (r:1 w:1) 
	// Storage: Opinion OpinionByOwner (r:1 w:1) 
	// Storage: Opinion Opinions (r:0 w:1) 
	fn create() -> Weight { 
		122_600_000_u64
			.saturating_add(RocksDbWeight::get().reads(7_u64)) 
			.saturating_add(RocksDbWeight::get().writes(5_u64)) 
	} 
	// Storage: Opinion OpinionAdminKey (r:1 w:0) 
	// Storage: Opinion Opinions (r:1 w:1) 
	fn update() -> Weight { 
		59_900_000_u64
			.saturating_add(RocksDbWeight::get().reads(2_u64)) 
			.saturating_add(RocksDbWeight::get().writes(1_u64)) 
	} 
	// Storage: Opinion OpinionAdminKey (r:1 w:0) 
	// Storage: Opinion Opinions (r:1 w:1) 
	// Storage: OpinionRequestor OpinionRequestors (r:1 w:1) 
	// Storage: Opinion OpinionCount (r:1 w:1) 
	// Storage: Opinion OpinionCountByOwner (r:1 w:1) 
	// Storage: Opinion OpinionByOwner (r:1 w:1) 
	fn delete() -> Weight { 
		99_100_000_u64
			.saturating_add(RocksDbWeight::get().reads(6_u64)) 
			.saturating_add(RocksDbWeight::get().writes(5_u64)) 
	} 
	// Storage: Opinion OpinionAdminKey (r:1 w:1) 
	fn update_admin_key() -> Weight { 
		35_700_000_u64
			.saturating_add(RocksDbWeight::get().reads(1_u64)) 
			.saturating_add(RocksDbWeight::get().writes(1_u64)) 
	} 
}
