//! Autogenerated weights for opinion_requestor_benchmarking
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-12-14, STEPS: `20`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/debio
// benchmark
// --chain=dev
// --execution=wasm
// --wasm-execution=compiled
// --pallet=opinion-requestor-benchmarking
// --extrinsic=*
// --steps=20
// --repeat=10
// --heap-pages=4096
// --output=./pallets/opinion-requestor/src/weights.rs
// --template=./.maintain/pallet-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for opinion_requestor_benchmarking.
pub trait WeightInfo { 
	fn request_opinion() -> Weight; 
	fn update_requestor_info() -> Weight; 
}

/// Weights for opinion_requestor_benchmarking using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>); 
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> { 
	// Storage: OpinionRequestor OpinionRequestorCount (r:1 w:1) 
	// Storage: Timestamp Now (r:1 w:0) 
	// Storage: OpinionRequestor OpinionRequestorByOwner (r:1 w:1) 
	// Storage: OpinionRequestor OpinionRequestorCountByOwner (r:1 w:1) 
	// Storage: OpinionRequestor OpinionRequestors (r:0 w:1) 
	fn request_opinion() -> Weight { 
		75_300_000_u64 
			.saturating_add(T::DbWeight::get().reads(4_u64)) 
			.saturating_add(T::DbWeight::get().writes(4_u64)) 
	}
	// Storage: Timestamp Now (r:1 w:0) 
	// Storage: OpinionRequestor OpinionRequestors (r:1 w:1) 
	fn update_requestor_info() -> Weight { 
		95_400_000_u64 
			.saturating_add(T::DbWeight::get().reads(2_u64)) 
			.saturating_add(T::DbWeight::get().writes(1_u64)) 
	}
}

// For backwards compatibility and tests
impl WeightInfo for () { 
	// Storage: OpinionRequestor OpinionRequestorCount (r:1 w:1) 
	// Storage: Timestamp Now (r:1 w:0) 
	// Storage: OpinionRequestor OpinionRequestorByOwner (r:1 w:1) 
	// Storage: OpinionRequestor OpinionRequestorCountByOwner (r:1 w:1) 
	// Storage: OpinionRequestor OpinionRequestors (r:0 w:1) 
	fn request_opinion() -> Weight { 
		75_300_000_u64
			.saturating_add(RocksDbWeight::get().reads(4_u64)) 
			.saturating_add(RocksDbWeight::get().writes(4_u64)) 
	} 
	// Storage: Timestamp Now (r:1 w:0) 
	// Storage: OpinionRequestor OpinionRequestors (r:1 w:1) 
	fn update_requestor_info() -> Weight { 
		95_400_000_u64
			.saturating_add(RocksDbWeight::get().reads(2_u64)) 
			.saturating_add(RocksDbWeight::get().writes(1_u64)) 
	} 
}
